/** Hungarian texts of the app shell (sign-in, child picker, therapist view); texts.js picks the active language. */
export default {
  tagline: 'Játékos beszéd- és iskolaelőkészítő gyakorlás 4–7 éveseknek.',
  google: 'Bejelentkezés Google-fiókkal',
  demo: 'Demó belépés',
  googleSetup: 'Google-belépéshez állítsd be a GOOGLE_CLIENT_ID és GOOGLE_CLIENT_SECRET értékét.',
  noLogin: 'A bejelentkezés most nem érhető el.',
  parentsOnly: 'Szülőként jelentkezz be. A gyerekek eredményei a te fiókodhoz tartoznak, és csak te látod őket.',
  errors: {
    cancelled: 'A Google-belépés megszakadt. Próbáld újra!',
    failed: 'Nem sikerült a Google-belépés. Próbáld újra!',
    email_taken: 'Ezzel az e-mail-címmel már van fiók, de a Google nem igazolta. Jelentkezz be a régi módon.',
    server: 'A szerver most nem érhető el. Próbáld újra kicsit később!',
    demo: 'Nem sikerült a demó belépés.',
  },
  auth: {
    login: 'Belépés',
    register: 'Regisztráció',
    name: 'Neved',
    email: 'E-mail-cím',
    password: 'Jelszó',
    newPassword: 'Új jelszó',
    passwordHint: 'Legalább 10 karakter, betűk és számok.',
    loginSubmit: 'Belépek',
    registerSubmit: 'Fiók létrehozása',
    forgot: 'Elfelejtett jelszó',
    forgotSubmit: 'Küldd el a linket',
    forgotSent: 'Ha van fiók ezzel az e-mail-címmel, elküldtük a jelszó-visszaállító linket. Nézd meg a postaládád!',
    // In the app the e-mailed link opens the website in the browser.
    forgotSentNative:
      'Ha van fiók ezzel az e-mail-címmel, elküldtük a jelszó-visszaállító linket. A levélben lévő link a böngészőben nyílik meg: ott add meg az új jelszót, aztán gyere vissza ide, és lépj be vele.',
    or: 'vagy',
    backToLogin: 'Vissza a belépéshez',
    resetTitle: 'Új jelszó',
    resetSubmit: 'Új jelszó mentése',
    resetNoToken: 'Ez a link nem érvényes. Kérj új jelszó-visszaállító levelet a belépésnél!',
    resetFailed: 'Nem sikerült az új jelszót beállítani.',
    failed: 'Nem sikerült. Próbáld újra!',
    agree: 'A fiók létrehozásával elfogadod a',
    terms: 'Felhasználási feltételeket',
    and: 'és az',
    privacy: 'Adatkezelési tájékoztatót',
  },
  whoPlays: 'Ki játszik ma?',
  addChild: 'Új gyerek',
  childName: 'Hogy hívják a gyermeked?',
  childNamePlaceholder: 'pl. Zoé',
  birthDate: 'Születési dátum (nem kötelező)',
  birthDateHint: 'Ebből tudjuk, milyen nehéz feladatokkal kezdjünk.',
  sign: 'Az óvodai jel',
  pickSign: 'Jel választása',
  signOf: '{name} óvodai jele',
  birthDateOf: '{name} születési dátuma',
  contentEditor: 'Tartalomszerkesztő',
  save: 'Mentés',
  cancel: 'Mégse',
  edit: 'Szerkesztés',
  done: 'Kész',
  remove: '{name} törlése',
  removeConfirm: 'Biztosan törlöd {name} összes adatát (eredmények, matricák)? Ez nem vonható vissza.',
  logout: 'Kijelentkezés',
  saveFailed: 'Nem sikerült menteni.',
  firstChild: 'Add hozzá a gyermeked, és kezdődhet a játék!',

  privacyLink: 'Adatvédelem',
  exportData: 'Adataim letöltése',
  milestoneEmails: 'E-mail, ha a gyermekem elért egy mérföldkövet',
  milestoneEmailsSaveFailed: 'Nem sikerült elmenteni ezt a beállítást.',
  weeklyReport: 'Heti beszámoló e-mailben vasárnap este, PDF-fel',
  playReminder: 'Esti emlékeztető e-mailben, ha ma még nem játszottatok',
  legalNav: 'Jogi tájékoztatók',
  legalPrivacy: 'Adatvédelem',
  legalTerms: 'ÁSZF',
  legalCookies: 'Sütik',
  legalImprint: 'Impresszum',
  weeklySample: 'Küldd el most a heti beszámolót',
  weeklySampleSending: 'Küldjük…',
  weeklySampleSent: 'Elküldtük ({count} levél) ide: {email}',
  weeklySampleNone: 'Ezen a héten még senki nem játszott, így nincs miről beszámolni.',
  weeklySampleWait: 'Most küldtünk egyet, próbáld újra pár perc múlva!',
  deleteAccount: 'Fiók törlése',
  deletePrompt:
    'A fiókod, az összes gyerek, minden eredmény, matrica és hangfelvétel véglegesen törlődik. Ha biztos vagy benne, írd be: TÖRLÉS',
  deleteWord: 'TÖRLÉS',
  deleteFailed: 'Nem sikerült törölni a fiókot.',

  consent: {
    title: 'Mielőtt kezdünk',
    intro:
      'Az alkalmazás elmenti a gyerekek játékeredményeit, hogy lásd a haladásukat, és a játékok hozzájuk igazodjanak. Ehhez a te hozzájárulásodra van szükség.',
    stored: 'Mit tárolunk',
    storedItems: [
      'a te neved és e-mail-címed (a bejelentkezéshez);',
      'a gyerek keresztnevét (és ha megadod, a születési dátumát);',
      'a játékok eredményeit, szintjeit és matricáit;',
      'a hangfelvételeidet, ha készítesz.',
    ],
    rights: 'Az adataidat bármikor letöltheted vagy törölheted a „Ki játszik?” oldalon.',
    checkbox: 'Szülőként elolvastam az adatkezelési tájékoztatót, és hozzájárulok, hogy a gyerekeim eredményeit az alkalmazás tárolja.',
    accept: 'Elfogadom',
    failed: 'Nem sikerült menteni. Próbáld újra!',
  },

  /** What the therapist sees behind a share link (pages/SharePage.vue). */
  share: {
    expired: 'Ez a link lejárt, vagy a szülő visszavonta. Kérj tőle újat.',
    loadFailed: 'Most nem sikerült betölteni. Próbáld újra kicsit később.',
    loading: 'Betöltés…',
    docTitle: '{name} – haladás',
    kicker: 'Beszéd – haladási összefoglaló',
    period: '{since} – {generated} · a link érvényes: {expires}',
    print: 'Nyomtatás',
    summary: 'Összefoglaló',
    perGame: 'Játékonként',
    noPlay: 'Ebben az időszakban még nem volt játék.',
    columns: {
      game: 'Játék',
      skill: 'Mit gyakorol',
      sessions: 'Végigjátszva',
      answers: 'Válaszok',
      firstTry: 'Elsőre jó',
      level: 'Szint',
      last: 'Utoljára',
    },
    foot:
      'Az adatok egy otthoni gyakorlóalkalmazásból származnak: „elsőre jó” = a gyerek első próbálkozásra jól ' +
      'válaszolt. Ez nem standardizált mérés és nem diagnózis; a szülő bármikor visszavonhatja a linket.',
  },
}
