/**
 * Textos en español latinoamericano (neutro, con "tú") de la app; las mismas claves que texts.hu.js (tests/js/i18n.test.mjs lo comprueba).
 * El aviso de consentimiento y el texto de eliminación de la cuenta son traducciones simples de los borradores en húngaro:
 * hay que revisarlos junto con el aviso de privacidad antes de que familias reales usen la versión en español.
 */
export default {
  tagline: 'Práctica lúdica del habla y preparación para la escuela, para niños de 4 a 7 años.',
  google: 'Iniciar sesión con Google',
  demo: 'Inicio de sesión de prueba',
  googleSetup: 'Para activar el inicio de sesión con Google, configura GOOGLE_CLIENT_ID y GOOGLE_CLIENT_SECRET.',
  noLogin: 'Por ahora no es posible iniciar sesión.',
  parentsOnly: 'Inicia sesión como madre o padre. Los resultados de los niños pertenecen a tu cuenta y solo tú puedes verlos.',
  errors: {
    cancelled: 'Se canceló el inicio de sesión con Google. ¡Inténtalo de nuevo!',
    failed: 'Falló el inicio de sesión con Google. ¡Inténtalo de nuevo!',
    email_taken: 'Ya existe una cuenta con este correo electrónico, pero Google no lo verificó. Inicia sesión de la forma anterior.',
    server: 'El servidor no está disponible en este momento. ¡Inténtalo de nuevo un poco más tarde!',
    demo: 'Falló el inicio de sesión de prueba.',
  },
  auth: {
    login: 'Iniciar sesión',
    register: 'Cuenta nueva',
    name: 'Tu nombre',
    email: 'Correo electrónico',
    password: 'Contraseña',
    newPassword: 'Contraseña nueva',
    passwordHint: 'Al menos 10 caracteres, con letras y números.',
    loginSubmit: 'Iniciar sesión',
    registerSubmit: 'Crear cuenta',
    forgot: 'Olvidé mi contraseña',
    forgotSubmit: 'Envíame el enlace',
    forgotSent: 'Si existe una cuenta con este correo electrónico, enviamos el enlace para restablecer la contraseña. ¡Revisa tu bandeja de entrada!',
    // In the app the e-mailed link opens the website in the browser.
    forgotSentNative:
      'Si existe una cuenta con este correo electrónico, enviamos el enlace para restablecer la contraseña. El enlace del correo se abre en tu navegador: crea ahí la contraseña nueva, luego regresa aquí e inicia sesión con ella.',
    or: 'o',
    backToLogin: 'Volver al inicio de sesión',
    resetTitle: 'Contraseña nueva',
    resetSubmit: 'Guardar la contraseña nueva',
    resetNoToken: 'Este enlace no es válido. ¡Solicita un nuevo correo para restablecer la contraseña en la página de inicio de sesión!',
    resetFailed: 'No se pudo establecer la contraseña nueva.',
    failed: 'No funcionó. ¡Inténtalo de nuevo!',
    agree: 'Al crear una cuenta aceptas los',
    terms: 'Términos de uso',
    and: 'y el',
    privacy: 'Aviso de privacidad',
  },
  whoPlays: '¿Quién juega hoy?',
  addChild: 'Niño o niña nuevo',
  childName: '¿Cómo se llama el niño o la niña?',
  childNamePlaceholder: 'p. ej., Zoé',
  birthDate: 'Fecha de nacimiento (opcional)',
  birthDateHint: 'Así sabemos qué tan difíciles deben ser las primeras tareas.',
  sign: 'Símbolo del jardín de niños',
  pickSign: 'Elige un símbolo',
  signOf: 'Símbolo de {name} del jardín de niños',
  birthDateOf: 'Fecha de nacimiento de {name}',
  contentEditor: 'Editor de contenido',
  save: 'Guardar',
  cancel: 'Cancelar',
  edit: 'Editar',
  done: 'Listo',
  remove: 'Eliminar a {name}',
  removeConfirm: '¿Seguro que quieres eliminar todos los datos de {name} (resultados, stickers)? Esta acción no se puede deshacer.',
  logout: 'Cerrar sesión',
  saveFailed: 'No se pudo guardar.',
  firstChild: '¡Agrega a tu primer niño o niña y los juegos pueden empezar!',

  privacyLink: 'Privacidad',
  exportData: 'Descargar mis datos',
  milestoneEmails: 'Enviarme un correo cuando el niño o la niña alcance un logro',
  milestoneEmailsSaveFailed: 'No se pudo guardar este ajuste.',
  weeklyReport: 'Resumen semanal por correo el domingo por la noche, con un PDF',
  playReminder: 'Enviarme un correo por la noche si hoy no hemos jugado',
  legalNav: 'Información legal',
  legalPrivacy: 'Privacidad',
  legalTerms: 'Términos',
  legalCookies: 'Cookies',
  legalImprint: 'Aviso legal',
  weeklySample: 'Enviar el resumen semanal ahora',
  weeklySampleSending: 'Enviando…',
  weeklySampleSent: 'Enviado ({count} correo(s)) a {email}',
  weeklySampleNone: 'Todavía nadie ha jugado esta semana, así que no hay nada que informar.',
  weeklySampleWait: 'Acabamos de enviar uno; ¡inténtalo de nuevo en unos minutos!',
  deleteAccount: 'Eliminar cuenta',
  deletePrompt:
    'Tu cuenta, todos los niños, todos los resultados, stickers y grabaciones de voz se eliminarán de forma permanente. Si estás seguro, escribe: ELIMINAR',
  deleteWord: 'ELIMINAR',
  deleteFailed: 'No se pudo eliminar la cuenta.',

  consent: {
    title: 'Antes de empezar',
    intro:
      'La app guarda los resultados de los juegos de los niños para que puedas ver su progreso y para que los juegos se adapten a ellos. Para esto necesitamos tu consentimiento.',
    stored: 'Qué guardamos',
    storedItems: [
      'tu nombre y correo electrónico (para iniciar sesión);',
      'el nombre de pila del niño o la niña (y, si lo indicas, su fecha de nacimiento);',
      'los resultados, niveles y stickers de los juegos;',
      'tus grabaciones de voz, si haces alguna.',
    ],
    rights: 'Puedes descargar o eliminar tus datos en cualquier momento en la página "¿Quién juega?".',
    checkbox: 'Como madre o padre, leí el aviso de privacidad y doy mi consentimiento para que la app guarde los resultados de mis hijos.',
    accept: 'Acepto',
    failed: 'No se pudo guardar. ¡Inténtalo de nuevo!',
  },

  /** What the therapist sees behind a share link (pages/SharePage.vue). */
  share: {
    expired: 'Este enlace venció o la madre o el padre lo revocó. Pídele uno nuevo.',
    loadFailed: 'No se pudo cargar en este momento. Inténtalo de nuevo un poco más tarde.',
    loading: 'Cargando…',
    docTitle: '{name} – progreso',
    kicker: 'Beszéd – resumen de progreso',
    period: '{since} – {generated} · el enlace es válido hasta el {expires}',
    print: 'Imprimir',
    summary: 'Resumen',
    perGame: 'Por juego',
    noPlay: 'No se jugó ningún juego en este período.',
    columns: {
      game: 'Juego',
      skill: 'Qué practica',
      sessions: 'Completadas',
      answers: 'Respuestas',
      firstTry: 'Correctas al primer intento',
      level: 'Nivel',
      last: 'Última vez que jugó',
    },
    foot:
      'Los datos provienen de una app de práctica en casa: "correctas al primer intento" = el niño respondió bien en el primer ' +
      'intento. No es una medida estandarizada ni un diagnóstico; la madre o el padre puede revocar el enlace en cualquier momento.',
  },
}
