/**
 * English texts of the app shell; the same keys as texts.hu.js (tests/js/i18n.test.mjs checks that).
 * The consent notice and the account-deletion wording are plain translations of the Hungarian drafts:
 * have them reviewed together with the privacy notice before real families use the English version.
 */
export default {
  tagline: 'Playful speech and school-readiness practice for ages 4–7.',
  google: 'Sign in with Google',
  demo: 'Demo sign-in',
  googleSetup: 'To enable Google sign-in, set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET.',
  noLogin: 'Signing in is not available right now.',
  parentsOnly: "Sign in as a parent. The children's results belong to your account, and only you can see them.",
  errors: {
    cancelled: 'Google sign-in was cancelled. Try again!',
    failed: 'Google sign-in failed. Try again!',
    email_taken: 'An account with this e-mail address already exists, but Google did not verify it. Sign in the old way.',
    server: 'The server is not available right now. Please try again a little later!',
    demo: 'Demo sign-in failed.',
  },
  auth: {
    login: 'Sign in',
    register: 'New account',
    name: 'Your name',
    email: 'E-mail address',
    password: 'Password',
    newPassword: 'New password',
    passwordHint: 'At least 10 characters, letters and numbers.',
    loginSubmit: 'Sign in',
    registerSubmit: 'Create account',
    forgot: 'Forgot password',
    forgotSubmit: 'Send me the link',
    forgotSent: "If there is an account with this e-mail address, we've sent the password reset link. Check your inbox!",
    // In the app the e-mailed link opens the website in the browser.
    forgotSentNative:
      "If there is an account with this e-mail address, we've sent the password reset link. The link in the e-mail opens in your browser: set the new password there, then come back here and sign in with it.",
    or: 'or',
    backToLogin: 'Back to sign-in',
    resetTitle: 'New password',
    resetSubmit: 'Save new password',
    resetNoToken: 'This link is not valid. Request a new password reset e-mail on the sign-in page!',
    resetFailed: "Couldn't set the new password.",
    failed: "That didn't work. Try again!",
    agree: 'By creating an account you accept the',
    terms: 'Terms of Use',
    and: 'and the',
    privacy: 'Privacy Notice',
  },
  whoPlays: 'Who is playing today?',
  addChild: 'New child',
  childName: "What is the child's name?",
  childNamePlaceholder: 'e.g. Zoé',
  birthDate: 'Date of birth (optional)',
  birthDateHint: 'This tells us how hard the first tasks should be.',
  sign: 'Kindergarten sign',
  signHint: "Pick your sign, like the one on your towel at nursery! It's how you recognise yourself here, too.",
  pickSign: 'Pick a sign',
  signOf: "{name}'s kindergarten sign",
  birthDateOf: "{name}'s date of birth",
  contentEditor: 'Content editor',
  save: 'Save',
  cancel: 'Cancel',
  edit: 'Edit',
  done: 'Done',
  remove: 'Delete {name}',
  removeConfirm: "Are you sure you want to delete all of {name}'s data (results, stickers)? This cannot be undone.",
  logout: 'Sign out',
  saveFailed: "Couldn't save.",
  firstChild: 'Add your first child and the games can begin!',

  privacyLink: 'Privacy',
  exportData: 'Download my data',
  milestoneEmails: 'E-mail me when the child reaches a milestone',
  milestoneEmailsSaveFailed: "Couldn't save this setting.",
  weeklyReport: 'Weekly summary by e-mail on Sunday evening, with a PDF',
  playReminder: "E-mail me in the evening if we haven't played today",
  weeklySample: 'Send the weekly summary now',
  weeklySampleSending: 'Sending…',
  weeklySampleSent: 'Sent ({count} e-mail(s)) to {email}',
  weeklySampleNone: 'Nobody has played this week yet, so there is nothing to report.',
  weeklySampleWait: 'We just sent one; try again in a few minutes!',
  deleteAccount: 'Delete account',
  deletePrompt:
    'Your account, all children, every result, sticker and voice recording will be deleted permanently. If you are sure, type: DELETE',
  deleteWord: 'DELETE',
  deleteFailed: "Couldn't delete the account.",

  consent: {
    title: 'Before we start',
    intro:
      "The app saves the children's game results so you can see their progress and the games can adapt to them. This needs your consent.",
    stored: 'What we store',
    storedItems: [
      'your name and e-mail address (for signing in);',
      "the child's first name (and, if you give it, their date of birth);",
      'the results, levels and stickers from the games;',
      'your voice recordings, if you make any.',
    ],
    rights: 'You can download or delete your data at any time on the "Who is playing?" page.',
    checkbox: "As a parent I have read the privacy notice, and I consent to the app storing my children's results.",
    accept: 'I accept',
    failed: "Couldn't save. Try again!",
  },

  /** What the therapist sees behind a share link (pages/SharePage.vue). */
  share: {
    expired: 'This link has expired, or the parent has revoked it. Ask them for a new one.',
    loadFailed: "Couldn't load it right now. Please try again a little later.",
    loading: 'Loading…',
    docTitle: '{name} – progress',
    kicker: 'Beszéd – progress summary',
    period: '{since} – {generated} · the link is valid until {expires}',
    print: 'Print',
    summary: 'Summary',
    perGame: 'By game',
    noPlay: 'No games were played in this period.',
    columns: {
      game: 'Game',
      skill: 'What it practises',
      sessions: 'Completed',
      answers: 'Answers',
      firstTry: 'Right first time',
      level: 'Level',
      last: 'Last played',
    },
    foot:
      'The data comes from a home practice app: "right first time" = the child answered correctly on the first ' +
      'attempt. This is not a standardised measure and not a diagnosis; the parent can revoke the link at any time.',
  },
}
